apiVersion: redpanda.vectorized.io/v1alpha1
kind: TopicContractSet
metadata:
  name: erp-ecommerce-topics
  generatedAt: "2026-02-28"
spec:
  broker: redpanda
  envelope:
    required:
      - event_id
      - tenant_id
      - event_type
      - occurred_at
      - producer
      - schema_version
  topics:
    - name: ecommerce.orders
      partitions: 12
      replicationFactor: 3
      retentionMs: 604800000
      cleanupPolicy: compact,delete
      schemaRef: contracts/ecommerce_orders.avsc
      compaction:
        enabled: true
        minCleanableDirtyRatio: 0.5
        deleteRetentionMs: 86400000
      tieredStorage:
        enabled: true
        localRetentionMs: 86400000
        remoteRetentionMs: 2592000000
      dlq:
        enabled: true
        maxRetries: 3
        retryBackoffMs: [1000, 10000, 60000]
        dlqTopic: "ecommerce.orders.dlq"
        dlqRetentionMs: 2592000000
    - name: ecommerce.catalog
      partitions: 12
      replicationFactor: 3
      retentionMs: 604800000
      cleanupPolicy: compact,delete
      schemaRef: contracts/ecommerce_catalog.avsc
      compaction:
        enabled: true
        minCleanableDirtyRatio: 0.5
        deleteRetentionMs: 86400000
      tieredStorage:
        enabled: true
        localRetentionMs: 86400000
        remoteRetentionMs: 2592000000
      dlq:
        enabled: true
        maxRetries: 3
        retryBackoffMs: [1000, 10000, 60000]
        dlqTopic: "ecommerce.catalog.dlq"
        dlqRetentionMs: 2592000000
    - name: ecommerce.customer
      partitions: 12
      replicationFactor: 3
      retentionMs: 604800000
      cleanupPolicy: compact,delete
      schemaRef: contracts/ecommerce_customer.avsc
      compaction:
        enabled: true
        minCleanableDirtyRatio: 0.5
        deleteRetentionMs: 86400000
      tieredStorage:
        enabled: true
        localRetentionMs: 86400000
        remoteRetentionMs: 2592000000
      dlq:
        enabled: true
        maxRetries: 3
        retryBackoffMs: [1000, 10000, 60000]
        dlqTopic: "ecommerce.customer.dlq"
        dlqRetentionMs: 2592000000
