# Redpanda Connect pipeline: Tenant-aware event routing for erp-ecommerce
# Routes events to tenant-specific topics based on x-tenant-id header
input:
  kafka:
    addresses: ["${CONNECT_BROKERS:redpanda:9092}"]
    topics: ["ecommerce.*"]
    consumer_group: "erp-ecommerce-tenant-router"
    batching:
      count: 100
      period: 1s

pipeline:
  processors:
    - branch:
        request_map: |
          root = if this.metadata("x-tenant-id") == null {
            throw("missing x-tenant-id header")
          }
          root.tenant_id = this.metadata("x-tenant-id")
          root.source_topic = this.metadata("kafka_topic")
        processors:
          - log:
              level: DEBUG
              message: "routing event for tenant ${!this.tenant_id} from ${!this.source_topic}"
        result_map: |
          root = this
          meta x-routed = "true"
    - switch:
        - check: this.metadata("x-tenant-id") == ""
          processors:
            - mapping: |
                root = this
                meta kafka_topic = "ecommerce.dlq.unrouted"
        - processors:
            - mapping: |
                let tenant = this.metadata("x-tenant-id")
                let original_topic = this.metadata("kafka_topic")
                root = this
                meta kafka_topic = "tenant.${!tenant}.${!original_topic}"

output:
  kafka:
    addresses: ["${CONNECT_BROKERS:redpanda:9092}"]
    topic: "${!metadata(\"kafka_topic\")}"
    headers:
      include_prefixes: ["x-"]
    metadata:
      include_prefixes: ["x-"]
    compression: lz4
